### ISSUE TITLE
Trouble Browsing Metrics

### ISSUE THREAD

**Issue by gomker** [Appdynamics/f5-monitoring-extension#1]
Has this been verified with 3.8.0.1
I am getting an error when trying to browse the metrics

"Invalid metric id:0 is specified
(metricBrowser.getMetricTreeRootsSpecifiedMetricsExpanded)"

The tree will refresh with the LB node data, but no metrics load.

Regards,

**Comment by abeytom07** [comment]
Hi Dave,
Could you please send the following?
1. machine-agent.log
2. Controller/logs/server.log ; if it is a saas controller let us know the url.

Thanks
Abey

**Comment by gomker** [comment]
Logs are here 
https://github.com/gomker/f5-monitoring-extension/tree/master/troubleshooting

Thanks

**Comment by gomker** [comment]
Old issue. Closing
